[package]
name = "Koze/playerdata"
version = "1.0.0"
description = "Reusable player data system with module registration"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
license = "MIT"

[dependencies]
ByteNet = "ffrostflame/bytenet@^0.1.0"

[server-dependencies]
ProfileStore = "madstudioroblox/profilestore@^1.0.0"